dependencies:
  #-<organization/<version-name>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
dotenv: .env
settings:
  gas_limit: "100000000000"
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  development:
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
  rinkeby:
    eth_usd_address: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    fee: 100000000000000000
    verify: True
  mainnet-fork-dev:
    eth_usd_address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  mainnet-fork:
    eth_usd_address: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
